name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:  # allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and test

    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install package and dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install -r requirements.txt
        
      - name: Test with pytest
        run: |
          python -m pytest tests/test_back.py
          python -m pytest tests/test_tools.py
          python -m pytest tests/test_masks.py
          python -m pytest tests/test_basic_beam_size.py
          python -m pytest tests/test_noise.py
          python -m pytest tests/test_no_noise.py
          python -m pytest tests/test_iso_noise.py
